[package]
name = "ab-contract-file"
description = "Utilities for working with contract files"
license = "0BSD"
version = "0.0.1"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]
links = "ab-contract-file"

[package.metadata.docs.rs]
all-features = true

[dependencies]
ab-io-type = { workspace = true }
ab-contracts-common = { workspace = true }
ab-riscv-interpreter = { workspace = true }
ab-riscv-macros = { workspace = true, features = ["proc-macro"] }
ab-riscv-primitives = { workspace = true }
ouroboros = { workspace = true }
replace_with = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
ab-riscv-macros = { workspace = true, features = ["build"] }

[lints]
workspace = true
