[package]
name = "ab-networking"
description = "Networking functionality for Abundance, primarily used for DSN (Distributed Storage Network)"
license = "0BSD"
version = "0.1.0"
authors = [
    "Nazar Mokrynskyi <nazar@mokrynskyi.com>",
    "Shamil Gadelshin <shamilgadelshin@gmail.com>"
]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
ab-cli-utils = { workspace = true }
ab-core-primitives = { workspace = true, features = ["alloc", "scale-codec"] }
async-lock = { workspace = true, features = ["std"] }
async-trait = { workspace = true }
backoff = { workspace = true, features = ["futures", "tokio"] }
blake3 = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, features = ["color", "derive"] }
derive_more = { workspace = true, features = ["full"] }
event-listener-primitives = { workspace = true }
fs2 = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
hex = { workspace = true }
memmap2 = { workspace = true }
multihash = { workspace = true, features = ["scale-codec"] }
nohash-hasher = { workspace = true }
parity-scale-codec = { workspace = true, features = ["std"] }
parking_lot = { workspace = true }
pin-project = { workspace = true }
prometheus-client = { workspace = true }
rand = { workspace = true, features = ["thread_rng"] }
schnellru = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-stream = { workspace = true }
tracing = { workspace = true }
unsigned-varint = { workspace = true, features = ["futures", "asynchronous_codec"] }
void = { workspace = true }
libp2p = { workspace = true, features = ["autonat", "dns", "gossipsub", "identify", "kad", "macros", "metrics", "noise", "ping", "plaintext", "request-response", "serde", "tcp", "tokio", "yamux"] }

[dev-dependencies]
rand = { workspace = true }
libp2p-swarm-test = { workspace = true }

[lints]
workspace = true
