[package]
name = "ab-client-block-builder"
description = "Block authoring implementation"
license = "0BSD"
version = "0.0.1"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

[dependencies]
ab-client-api = { workspace = true }
ab-client-consensus-common = { workspace = true }
ab-core-primitives = { workspace = true, features = ["alloc"] }
anyhow = { workspace = true }
rclite = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
