[package]
name = "ab-farmer-rpc-primitives"
description = "RPC primitives for the farmer"
license = "0BSD"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
ab-core-primitives = { workspace = true, features = ["scale-codec", "serde"] }
ab-farmer-components = { workspace = true }
ab-networking = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
