[package]
name = "ab-node"
description = "Consensus node CLI"
license = "0BSD"
version = "0.0.1"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

[dependencies]
ab-client-api = { workspace = true }
ab-client-archiving = { workspace = true }
ab-client-block-authoring = { workspace = true }
ab-client-block-builder = { workspace = true }
ab-client-block-import = { workspace = true }
ab-client-block-verification = { workspace = true }
ab-client-consensus-common = { workspace = true }
ab-client-database = { workspace = true }
ab-client-proof-of-time = { workspace = true }
ab-cli-utils = { workspace = true }
ab-core-primitives = { workspace = true, features = ["alloc"] }
ab-direct-io-file = { workspace = true }
ab-erasure-coding = { workspace = true }
ab-networking = { workspace = true }
ab-node-rpc-server = { workspace = true }
ab-proof-of-space = { workspace = true }
bytesize = { workspace = true }
clap = { workspace = true, features = ["derive"] }
core_affinity = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
jsonrpsee = { workspace = true, features = ["server"] }
mimalloc = { workspace = true }
rclite = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
thread-priority = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true, features = ["std"] }

[lints]
workspace = true
