[book]
title = "Project Abundance"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
language = "en"
multilingual = false

[build]
build-dir = "build"
create-missing = false

[preprocessor.alerts]

[preprocessor.d2]
dark-theme-id = "200"
layout = "elk"
theme-id = "1"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/nazar-pc/abundance/tree/main/book"
mathjax-support = true
preferred-dark-theme = "ayu"
